  
FROM jupyter/minimal-notebook:6d42503c684f
RUN /opt/conda/bin/conda install -c conda-forge pycalphad==0.8.3 espei==0.7.7 seaborn phonopy pymatgen pyiron lammps nodejs nglview && \
    python3 -m pip scheil --no-deps --no-cache-dir && \
    jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build && \
    jupyter labextension install nglview-js-widgets --no-build && \
    jupyter labextension disable @jupyterlab/filebrowser-extension:share-file --no-build && \
    jupyter labextension install jupyterhub-share-link-labextension
